-- Reshopy Phase 1 database setup
-- Target: PostgreSQL 14+
-- Run with: psql -d <database_name> -f database/reshopy.sql

BEGIN;

CREATE SCHEMA IF NOT EXISTS reshopy;
SET search_path TO reshopy, public;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS categories (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(120) NOT NULL,
    slug            varchar(140) NOT NULL UNIQUE,
    description     text,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT categories_name_not_blank CHECK (length(trim(name)) > 0)
);

CREATE TABLE IF NOT EXISTS customers (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      varchar(80) NOT NULL,
    last_name       varchar(80) NOT NULL,
    email           varchar(254) NOT NULL,
    password_hash   text NOT NULL,
    role            varchar(20) NOT NULL DEFAULT 'customer',
    phone           varchar(32),
    address_line1   varchar(200),
    address_line2   varchar(200),
    city            varchar(100),
    region          varchar(100),
    postal_code     varchar(24),
    country_code    char(2),
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT customers_role_check CHECK (role IN ('customer', 'admin')),
    CONSTRAINT customers_email_not_blank CHECK (length(trim(email)) > 3),
    CONSTRAINT customers_first_name_not_blank CHECK (length(trim(first_name)) > 0),
    CONSTRAINT customers_last_name_not_blank CHECK (length(trim(last_name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS customers_email_lower_uidx
    ON customers (lower(email));

CREATE TABLE IF NOT EXISTS products (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id         bigint NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    sku                 varchar(64) NOT NULL UNIQUE,
    name                varchar(180) NOT NULL,
    description         text,
    price               numeric(12, 2) NOT NULL,
    stock_quantity      integer NOT NULL DEFAULT 0,
    low_stock_threshold integer NOT NULL DEFAULT 5,
    image_url           text,
    is_active           boolean NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT products_name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT products_price_nonnegative CHECK (price >= 0),
    CONSTRAINT products_stock_nonnegative CHECK (stock_quantity >= 0),
    CONSTRAINT products_threshold_nonnegative CHECK (low_stock_threshold >= 0)
);

CREATE TABLE IF NOT EXISTS carts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL UNIQUE REFERENCES customers(id) ON DELETE CASCADE,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cart_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id     bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    product_id  bigint NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity    integer NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT cart_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT cart_items_cart_product_unique UNIQUE (cart_id, product_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number      text GENERATED ALWAYS AS ('RSH-' || lpad(id::text, 8, '0')) STORED UNIQUE,
    customer_id         bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    status              varchar(20) NOT NULL DEFAULT 'pending',
    payment_status      varchar(20) NOT NULL DEFAULT 'pending',
    payment_method      varchar(24) NOT NULL,
    currency            char(3) NOT NULL DEFAULT 'USD',
    subtotal            numeric(12, 2) NOT NULL,
    tax_amount          numeric(12, 2) NOT NULL DEFAULT 0,
    shipping_amount     numeric(12, 2) NOT NULL DEFAULT 0,
    discount_amount     numeric(12, 2) NOT NULL DEFAULT 0,
    total_amount        numeric(12, 2) GENERATED ALWAYS AS
                            (subtotal + tax_amount + shipping_amount - discount_amount) STORED,
    shipping_name       varchar(160) NOT NULL,
    shipping_address1   varchar(200) NOT NULL,
    shipping_address2   varchar(200),
    shipping_city       varchar(100) NOT NULL,
    shipping_region     varchar(100),
    shipping_postal_code varchar(24) NOT NULL,
    shipping_country    char(2) NOT NULL,
    placed_at           timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT orders_status_check CHECK (
        status IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')
    ),
    CONSTRAINT orders_payment_status_check CHECK (
        payment_status IN ('pending', 'paid', 'failed', 'refunded')
    ),
    CONSTRAINT orders_payment_method_check CHECK (
        payment_method IN ('card', 'paypal', 'cash_on_delivery')
    ),
    CONSTRAINT orders_amounts_nonnegative CHECK (
        subtotal >= 0 AND tax_amount >= 0 AND shipping_amount >= 0 AND discount_amount >= 0
    ),
    CONSTRAINT orders_discount_within_subtotal CHECK (discount_amount <= subtotal),
    CONSTRAINT orders_shipping_name_not_blank CHECK (length(trim(shipping_name)) > 0),
    CONSTRAINT orders_shipping_address_not_blank CHECK (length(trim(shipping_address1)) > 0)
);

CREATE TABLE IF NOT EXISTS order_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id      bigint NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    product_name    varchar(180) NOT NULL,
    product_sku     varchar(64) NOT NULL,
    unit_price      numeric(12, 2) NOT NULL,
    quantity        integer NOT NULL,
    line_total      numeric(14, 2) GENERATED ALWAYS AS (unit_price * quantity) STORED,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT order_items_price_nonnegative CHECK (unit_price >= 0),
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_items_order_product_unique UNIQUE (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS products_category_active_idx
    ON products (category_id, is_active);
CREATE INDEX IF NOT EXISTS products_active_name_idx
    ON products (lower(name)) WHERE is_active;
CREATE INDEX IF NOT EXISTS cart_items_product_idx
    ON cart_items (product_id);
CREATE INDEX IF NOT EXISTS orders_customer_placed_idx
    ON orders (customer_id, placed_at DESC);
CREATE INDEX IF NOT EXISTS orders_placed_status_idx
    ON orders (placed_at, status);
CREATE INDEX IF NOT EXISTS orders_paid_placed_idx
    ON orders (placed_at) WHERE payment_status = 'paid';
CREATE INDEX IF NOT EXISTS order_items_product_idx
    ON order_items (product_id);

-- These views keep the dashboard reports consistent across the admin interface.
CREATE OR REPLACE VIEW v_sales_report AS
WITH eligible_orders AS (
    SELECT id, placed_at, currency, subtotal, tax_amount, shipping_amount, discount_amount, total_amount
    FROM orders
    WHERE status NOT IN ('cancelled', 'refunded')
), daily_orders AS (
    SELECT date_trunc('day', placed_at)::date AS sales_date,
           currency,
           count(*) AS order_count,
           sum(subtotal) AS subtotal,
           sum(tax_amount) AS tax_amount,
           sum(shipping_amount) AS shipping_amount,
           sum(discount_amount) AS discount_amount,
           sum(total_amount) AS sales_total
    FROM eligible_orders
    GROUP BY date_trunc('day', placed_at)::date, currency
), daily_units AS (
    SELECT date_trunc('day', eo.placed_at)::date AS sales_date,
           eo.currency,
           sum(oi.quantity) AS units_sold
    FROM eligible_orders eo
    JOIN order_items oi ON oi.order_id = eo.id
    GROUP BY date_trunc('day', eo.placed_at)::date, eo.currency
)
SELECT d.sales_date, d.currency, d.order_count, coalesce(u.units_sold, 0) AS units_sold,
       d.subtotal, d.tax_amount, d.shipping_amount, d.discount_amount, d.sales_total
FROM daily_orders d
LEFT JOIN daily_units u USING (sales_date, currency);

CREATE OR REPLACE VIEW v_revenue_report AS
SELECT date_trunc('day', placed_at)::date AS revenue_date,
       currency,
       count(*) AS paid_order_count,
       sum(total_amount) AS recognized_revenue
FROM orders
WHERE payment_status = 'paid' AND status NOT IN ('cancelled', 'refunded')
GROUP BY date_trunc('day', placed_at)::date, currency;

CREATE OR REPLACE VIEW v_best_selling_products AS
SELECT p.id AS product_id,
       p.sku,
       p.name AS product_name,
       c.name AS category_name,
       sum(oi.quantity) AS units_sold,
       sum(oi.line_total) AS sales_total
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
JOIN products p ON p.id = oi.product_id
JOIN categories c ON c.id = p.category_id
WHERE o.status NOT IN ('cancelled', 'refunded')
GROUP BY p.id, p.sku, p.name, c.name;

CREATE OR REPLACE VIEW v_customer_purchase_history AS
SELECT c.id AS customer_id,
       c.first_name,
       c.last_name,
       c.email,
       o.id AS order_id,
       o.invoice_number,
       o.placed_at,
       o.status AS order_status,
       o.payment_status,
       o.currency,
       count(oi.id) AS line_count,
       coalesce(sum(oi.quantity), 0) AS units_purchased,
       o.total_amount
FROM customers c
JOIN orders o ON o.customer_id = c.id
LEFT JOIN order_items oi ON oi.order_id = o.id
GROUP BY c.id, c.first_name, c.last_name, c.email, o.id;

CREATE OR REPLACE VIEW v_inventory_report AS
SELECT p.id AS product_id,
       p.sku,
       p.name AS product_name,
       c.name AS category_name,
       p.price,
       p.stock_quantity,
       p.low_stock_threshold,
       (p.stock_quantity <= p.low_stock_threshold) AS is_low_stock,
       p.is_active
FROM products p
JOIN categories c ON c.id = p.category_id;

CREATE OR REPLACE VIEW v_category_sales_analysis AS
SELECT c.id AS category_id,
       c.name AS category_name,
       o.currency,
       sum(oi.quantity) AS units_sold,
       sum(oi.line_total) AS product_sales,
       count(DISTINCT o.id) AS order_count
FROM categories c
JOIN products p ON p.category_id = c.id
JOIN order_items oi ON oi.product_id = p.id
JOIN orders o ON o.id = oi.order_id
WHERE o.status NOT IN ('cancelled', 'refunded')
GROUP BY c.id, c.name, o.currency;

-- Atomically converts the customer's current cart into an order and decrements stock.
CREATE OR REPLACE PROCEDURE place_order(
    IN p_customer_id bigint,
    IN p_shipping_name text,
    IN p_shipping_address1 text,
    IN p_shipping_address2 text,
    IN p_shipping_city text,
    IN p_shipping_region text,
    IN p_shipping_postal_code text,
    IN p_shipping_country char(2),
    IN p_payment_method text,
    INOUT p_order_id bigint DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_cart_id bigint;
    v_item record;
    v_subtotal numeric(12, 2) := 0;
BEGIN
    IF nullif(trim(p_shipping_name), '') IS NULL
       OR nullif(trim(p_shipping_address1), '') IS NULL
       OR nullif(trim(p_shipping_city), '') IS NULL
       OR nullif(trim(p_shipping_postal_code), '') IS NULL
       OR nullif(trim(p_shipping_country), '') IS NULL THEN
        RAISE EXCEPTION 'Required shipping information is missing' USING ERRCODE = '22023';
    END IF;

    SELECT id INTO v_cart_id
    FROM carts
    WHERE customer_id = p_customer_id
    FOR UPDATE;

    IF v_cart_id IS NULL THEN
        RAISE EXCEPTION 'No cart exists for customer %', p_customer_id USING ERRCODE = 'P0002';
    END IF;

    FOR v_item IN
        SELECT ci.product_id, ci.quantity, p.name, p.sku, p.price, p.stock_quantity, p.is_active
        FROM cart_items ci
        JOIN products p ON p.id = ci.product_id
        WHERE ci.cart_id = v_cart_id
        ORDER BY ci.product_id
        FOR UPDATE OF ci, p
    LOOP
        IF NOT v_item.is_active THEN
            RAISE EXCEPTION 'Product % is no longer available', v_item.product_id USING ERRCODE = '22023';
        END IF;
        IF v_item.stock_quantity < v_item.quantity THEN
            RAISE EXCEPTION 'Insufficient stock for product %', v_item.product_id USING ERRCODE = '22023';
        END IF;
        v_subtotal := v_subtotal + (v_item.price * v_item.quantity);
    END LOOP;

    IF v_subtotal = 0 AND NOT EXISTS (SELECT 1 FROM cart_items WHERE cart_id = v_cart_id) THEN
        RAISE EXCEPTION 'Cannot place an order with an empty cart' USING ERRCODE = '22023';
    END IF;

    INSERT INTO orders (
        customer_id, status, payment_status, payment_method, subtotal,
        shipping_name, shipping_address1, shipping_address2, shipping_city,
        shipping_region, shipping_postal_code, shipping_country
    ) VALUES (
        p_customer_id, 'pending', 'pending', p_payment_method, v_subtotal,
        trim(p_shipping_name), trim(p_shipping_address1), nullif(trim(p_shipping_address2), ''),
        trim(p_shipping_city), nullif(trim(p_shipping_region), ''),
        trim(p_shipping_postal_code), upper(trim(p_shipping_country))
    ) RETURNING id INTO p_order_id;

    INSERT INTO order_items (order_id, product_id, product_name, product_sku, unit_price, quantity)
    SELECT p_order_id, p.id, p.name, p.sku, p.price, ci.quantity
    FROM cart_items ci
    JOIN products p ON p.id = ci.product_id
    WHERE ci.cart_id = v_cart_id;

    UPDATE products p
    SET stock_quantity = p.stock_quantity - ci.quantity,
        updated_at = now()
    FROM cart_items ci
    WHERE ci.cart_id = v_cart_id AND ci.product_id = p.id;

    DELETE FROM cart_items WHERE cart_id = v_cart_id;
    UPDATE carts SET updated_at = now() WHERE id = v_cart_id;
END;
$$;

-- Seed catalog and accounts. Seed account passwords are random and unrecoverable;
-- shoppers should register through the application to create usable credentials.
INSERT INTO categories (id, name, slug, description) VALUES
    (1, 'Home & Living', 'home-living', 'Thoughtful pieces for everyday spaces.'),
    (2, 'Accessories', 'accessories', 'Small details, made to last.'),
    (3, 'Stationery', 'stationery', 'Paper goods for plans and ideas.'),
    (4, 'Gifts', 'gifts', 'Considered gifts for every occasion.'),
    (5, 'Personal Care', 'personal-care', 'Daily essentials with a thoughtful touch.')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description;

INSERT INTO customers (
    id, first_name, last_name, email, password_hash, role, phone,
    address_line1, city, region, postal_code, country_code
) VALUES
    (1, 'Reshopy', 'Admin', 'admin@reshopy.test', crypt(gen_random_uuid()::text, gen_salt('bf')), 'admin', '+1-555-0100', '100 Market Street', 'Brooklyn', 'NY', '11201', 'US'),
    (2, 'Avery', 'Morgan', 'avery@example.test', crypt(gen_random_uuid()::text, gen_salt('bf')), 'customer', '+1-555-0101', '24 Willow Lane', 'Brooklyn', 'NY', '11211', 'US'),
    (3, 'Jordan', 'Lee', 'jordan@example.test', crypt(gen_random_uuid()::text, gen_salt('bf')), 'customer', '+1-555-0102', '8 Cedar Road', 'Queens', 'NY', '11101', 'US'),
    (4, 'Sam', 'Rivera', 'sam@example.test', crypt(gen_random_uuid()::text, gen_salt('bf')), 'customer', '+1-555-0103', '51 Orchard Street', 'New York', 'NY', '10002', 'US'),
    (5, 'Taylor', 'Chen', 'taylor@example.test', crypt(gen_random_uuid()::text, gen_salt('bf')), 'customer', '+1-555-0104', '17 Bergen Avenue', 'Brooklyn', 'NY', '11217', 'US')
ON CONFLICT (id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    phone = EXCLUDED.phone,
    address_line1 = EXCLUDED.address_line1,
    city = EXCLUDED.city,
    region = EXCLUDED.region,
    postal_code = EXCLUDED.postal_code,
    country_code = EXCLUDED.country_code;

INSERT INTO products (
    id, category_id, sku, name, description, price, stock_quantity, low_stock_threshold, image_url
) VALUES
    (1, 1, 'HOME-VASE-01', 'Ribbed Stoneware Vase', 'A sculptural matte-finish vase in warm white.', 48.00, 18, 4, 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d'),
    (2, 1, 'HOME-THROW-01', 'Woven Cotton Throw', 'Soft, textured cotton throw for slow evenings.', 86.00, 3, 5, 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0'),
    (3, 1, 'HOME-LAMP-01', 'Arc Table Lamp', 'Compact metal lamp with a warm ambient glow.', 124.00, 7, 3, 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c'),
    (4, 2, 'ACC-BAG-01', 'Everyday Canvas Tote', 'Heavyweight canvas tote with an interior pocket.', 32.00, 24, 6, 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7'),
    (5, 2, 'ACC-WALLET-01', 'Leather Card Holder', 'Slim vegetable-tanned leather card holder.', 54.00, 2, 4, 'https://images.unsplash.com/photo-1627123424574-724758594e93'),
    (6, 3, 'STAT-NOTE-01', 'Linen Notebook', 'Lay-flat notebook with 160 recycled pages.', 22.00, 35, 8, 'https://images.unsplash.com/photo-1531346878377-a5be20888e57'),
    (7, 3, 'STAT-PEN-01', 'Brass Gel Pen', 'Balanced brass pen with a smooth black ink refill.', 18.00, 12, 5, 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd'),
    (8, 4, 'GIFT-CANDLE-01', 'Cedar & Fig Candle', 'Small-batch soy candle with cedar and ripe fig notes.', 38.00, 16, 5, 'https://images.unsplash.com/photo-1603006905003-be475563bc59')
ON CONFLICT (id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    sku = EXCLUDED.sku,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    stock_quantity = EXCLUDED.stock_quantity,
    low_stock_threshold = EXCLUDED.low_stock_threshold,
    image_url = EXCLUDED.image_url;

INSERT INTO carts (id, customer_id) VALUES
    (1, 2),
    (2, 3),
    (3, 4),
    (4, 5),
    (5, 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cart_items (id, cart_id, product_id, quantity) VALUES
    (1, 1, 6, 2),
    (2, 1, 8, 1),
    (3, 2, 1, 1),
    (4, 2, 7, 2),
    (5, 3, 4, 1)
ON CONFLICT (id) DO UPDATE SET
    cart_id = EXCLUDED.cart_id,
    product_id = EXCLUDED.product_id,
    quantity = EXCLUDED.quantity;

INSERT INTO orders (
    id, customer_id, status, payment_status, payment_method, currency, subtotal,
    shipping_name, shipping_address1, shipping_city, shipping_region,
    shipping_postal_code, shipping_country, placed_at
) VALUES
    (1, 2, 'delivered', 'paid', 'card', 'USD', 130.00, 'Avery Morgan', '24 Willow Lane', 'Brooklyn', 'NY', '11211', 'US', now() - interval '18 days'),
    (2, 2, 'shipped', 'paid', 'paypal', 'USD', 102.00, 'Avery Morgan', '24 Willow Lane', 'Brooklyn', 'NY', '11211', 'US', now() - interval '4 days'),
    (3, 3, 'processing', 'paid', 'card', 'USD', 178.00, 'Jordan Lee', '8 Cedar Road', 'Queens', 'NY', '11101', 'US', now() - interval '2 days'),
    (4, 3, 'cancelled', 'refunded', 'card', 'USD', 54.00, 'Jordan Lee', '8 Cedar Road', 'Queens', 'NY', '11101', 'US', now() - interval '1 day'),
    (5, 4, 'confirmed', 'paid', 'card', 'USD', 70.00, 'Sam Rivera', '51 Orchard Street', 'New York', 'NY', '10002', 'US', now() - interval '12 hours')
ON CONFLICT (id) DO UPDATE SET
    customer_id = EXCLUDED.customer_id,
    status = EXCLUDED.status,
    payment_status = EXCLUDED.payment_status,
    payment_method = EXCLUDED.payment_method,
    currency = EXCLUDED.currency,
    subtotal = EXCLUDED.subtotal,
    shipping_name = EXCLUDED.shipping_name,
    shipping_address1 = EXCLUDED.shipping_address1,
    shipping_city = EXCLUDED.shipping_city,
    shipping_region = EXCLUDED.shipping_region,
    shipping_postal_code = EXCLUDED.shipping_postal_code,
    shipping_country = EXCLUDED.shipping_country,
    placed_at = EXCLUDED.placed_at;

INSERT INTO order_items (id, order_id, product_id, product_name, product_sku, unit_price, quantity) VALUES
    (1, 1, 1, 'Ribbed Stoneware Vase', 'HOME-VASE-01', 48.00, 1),
    (2, 1, 6, 'Linen Notebook', 'STAT-NOTE-01', 22.00, 2),
    (3, 1, 8, 'Cedar & Fig Candle', 'GIFT-CANDLE-01', 38.00, 1),
    (4, 2, 2, 'Woven Cotton Throw', 'HOME-THROW-01', 86.00, 1),
    (5, 2, 7, 'Brass Gel Pen', 'STAT-PEN-01', 16.00, 1),
    (6, 3, 3, 'Arc Table Lamp', 'HOME-LAMP-01', 124.00, 1),
    (7, 3, 4, 'Everyday Canvas Tote', 'ACC-BAG-01', 32.00, 1),
    (8, 3, 7, 'Brass Gel Pen', 'STAT-PEN-01', 22.00, 1),
    (9, 4, 5, 'Leather Card Holder', 'ACC-WALLET-01', 54.00, 1),
    (10, 5, 4, 'Everyday Canvas Tote', 'ACC-BAG-01', 32.00, 1),
    (11, 5, 6, 'Linen Notebook', 'STAT-NOTE-01', 22.00, 1),
    (12, 5, 7, 'Brass Gel Pen', 'STAT-PEN-01', 16.00, 1)
ON CONFLICT (id) DO UPDATE SET
    order_id = EXCLUDED.order_id,
    product_id = EXCLUDED.product_id,
    product_name = EXCLUDED.product_name,
    product_sku = EXCLUDED.product_sku,
    unit_price = EXCLUDED.unit_price,
    quantity = EXCLUDED.quantity;

-- Keep identity sequences ahead of the explicit sample IDs.
SELECT setval(pg_get_serial_sequence('categories', 'id'), greatest((SELECT coalesce(max(id), 1) FROM categories), 1));
SELECT setval(pg_get_serial_sequence('customers', 'id'), greatest((SELECT coalesce(max(id), 1) FROM customers), 1));
SELECT setval(pg_get_serial_sequence('products', 'id'), greatest((SELECT coalesce(max(id), 1) FROM products), 1));
SELECT setval(pg_get_serial_sequence('carts', 'id'), greatest((SELECT coalesce(max(id), 1) FROM carts), 1));
SELECT setval(pg_get_serial_sequence('cart_items', 'id'), greatest((SELECT coalesce(max(id), 1) FROM cart_items), 1));
SELECT setval(pg_get_serial_sequence('orders', 'id'), greatest((SELECT coalesce(max(id), 1) FROM orders), 1));
SELECT setval(pg_get_serial_sequence('order_items', 'id'), greatest((SELECT coalesce(max(id), 1) FROM order_items), 1));

COMMIT;